version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    # Disable version updates
    open-pull-requests-limit: 0
    ignore:
      # ignore all (non-security) patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
